---
# Archivo: vm_clone_from_template.yml
- name: Clone VM from Nutanix Template
  hosts: localhost
  gather_facts: false

  vars:
    vm_template_name: "{{ template_name }}"

  tasks:
    - name: Get list of all VMs (including templates)
      uri:
        url: "https://{{ prism }}:9440/api/nutanix/v3/vms/list"
        method: POST
        user: "{{ prism_user }}"
        password: "{{ prism_password }}"
        body:
          kind: "vm"
          offset: 0
          length: 100
        body_format: json
        headers:
          Content-Type: application/json
        force_basic_auth: yes
        validate_certs: no
        return_content: true
      register: vm_list_response

    - name: Debug raw VM list to find correct keys
      debug:
        var: vm_list_response.json.entities

    - name: Filter to find the template by name
      set_fact:
        matched_templates: "{{ vm_list_response.json.entities | selectattr('status.name', 'equalto', vm_template_name) | list }}"

    - name: Set template UUID from matched result
      set_fact:
        template_uuid: "{{ matched_templates[0].metadata.uuid }}"

    - name: Create clone request JSON file
      ansible.builtin.template:
        src: templates/clone_vm.json.j2
        dest: clone_vm.json

    - name: Clone VM from Template
      uri:
        url: "https://{{ prism }}:9440/api/nutanix/v3/vms/clones"
        user: "{{ prism_user }}"
        password: "{{ prism_password }}"
        method: POST
        body: "{{ lookup('file','clone_vm.json') }}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        headers:
          Content-Type: application/json
        status_code: 202
        return_content: true
      register: vm_clone_result

    - name: Get VM Attributes (wait for IP assignment)
      uri:
        url: "https://{{ prism }}:9440/api/nutanix/v3/vms/{{ vm_clone_result.json.metadata.uuid }}"
        user: "{{ prism_user }}"
        password: "{{ prism_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: no
        headers:
          Content-Type: application/json
        return_content: true
      register: get_vm_attributes
      retries: 10
      delay: 60
      until: get_vm_attributes.json.status.resources.nic_list[0].ip_endpoint_list[0].ip is defined

    - name: Capture VM IP for subsequent workflow
      ansible.builtin.set_stats:
        data:
          vm_ip: "{{ get_vm_attributes.json.status.resources.nic_list[0].ip_endpoint_list[0].ip }}"
